# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/golang-github-linuxdeepin-dbus-factory.spec

# add or remove files that should be synced
synced_files:
    - rpm/golang-github-linuxdeepin-dbus-factory.spec
    - .packit.yaml

upstream_package_name: go-dbus-factory
# downstream (Fedora) RPM package name
downstream_package_name: golang-github-linuxdeepin-dbus-factory

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"0,/Version:/ s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/golang-github-linuxdeepin-dbus-factory.spec"
