.PHONY: udev_info udev_info2
udev_info:udevinfo.c
	gcc -g  -w  -Wall -ludev udevinfo.c -o udev_info

udev_info2:udevinfo2.c
	gcc -g -Wall -ludev udevinfo2.c -o udev_info2


clean:
	rm udev_info udev_info2
